galaxy_info:
  author: yoshiaki tanaka
  description: install Debian Backports
  license: MIT
  min_ansible_version: 2.9
  platforms:
  - name: Debian
    versions:
      - stretch
      - buster
  galaxy_tags:
    - ansible

dependencies: []
