- name: Deploy Redmine
  hosts: all
  roles:
    - role: mariadb
    - role: redmine
    - role: nginx
  vars:
    tbls_version: "1.38.2"
  tasks:
    - name: create mysql connection file
      ini_file:
        path: ~/.my.cnf
        create: true
        section: client
        option: "{{ item.key | replace('_', '-') }}"
        value: "{{ item.value | string }}"
      with_dict:
        host: "{{ redmine_db_cfg.production.host }}"
        database: "{{ redmine_db_cfg.production.database }}"
        user: "{{ redmine_db_cfg.production.username }}"
        password: "{{ redmine_db_cfg.production.password }}"
        default_character_set: "{{ redmine_db_cfg.production.encoding }}"
      no_log: true
      become: false
    - name: download tbls
      get_url:
        url: "https://github.com/k1LoW/tbls/releases/download/v{{ tbls_version }}/tbls_{{ tbls_version }}-1_amd64.deb"
        dest: /tmp/tbls_{{ tbls_version }}-1_amd64.deb
    - name: install tbls
      apt:
        deb: /tmp/tbls_{{ tbls_version }}-1_amd64.deb
    - name: copy tbls commands
      copy:
        src: "{{ item }}"
        dest: "~/{{ item | basename }}"
        mode: "0755"
      loop: "{{ query('fileglob', 'scripts/tbls_*.sh') }}"
      become: false
    - block:
        - name: apply custom directory mapping
          file:
            dest: "{{ redmine_home }}/{{ item.dest }}"
            src: "/vagrant/{{ item.src }}"
            owner: "{{ redmine_user }}"
            group: "{{ redmine_user }}"
            state: link
          loop: "{{ redmine_custom_directory_mappings }}"
          notify: restart redmine
          register: result
        - block:
            - name: execute bundle install
              command: bundle install
              args:
                chdir: "{{ redmine_home }}"
            - name: execute bundle exec rake db:migrate
              command: bundle exec rake db:migrate
              args:
                chdir: "{{ redmine_home }}"
            - name: execute bundle exec rake redmine:plugins:migrate
              command: bundle exec rake redmine:plugins:migrate
              args:
                chdir: "{{ redmine_home }}"
          when: result is changed
      when: redmine_custom_directory_mappings is defined
    - name: Finish display message
      debug:
        msg: "Let's Redmine!"
