---
- name: checkout source
  ansible.builtin.git:
    repo: https://github.com/microsoft/pict.git
    dest: /usr/local/src/pict
    version: main
  register: git_result
- name: build
  ansible.builtin.command: make
  args:
    chdir: /usr/local/src/pict
  when: git_result is changed
- name: create symlink
  ansible.builtin.file:
    src: /usr/local/src/pict/pict
    dest: /usr/local/bin/pict
    state: link
