---
- hosts: all
  roles:
    - role: nginx
  tasks:
    - name: remove default setting file
      file:
        path: "/etc/nginx/{{ item }}/default"
        state: absent
      with_items:
        - sites-available
        - sites-enabled
  pre_tasks:
    - name: dump vars
      block:
        - name: create dump directory
          file:
            path: .molecule/facts
            state: directory
          changed_when: no
        - name: dump host gether facts
          blockinfile:
            path: ".molecule/facts/{{ inventory_hostname }}.yml"
            create: yes
            block: "{{ vars | to_nice_yaml }}"
          changed_when: no
      connection: local
      become: no
