- name: load default langage data file
  command: cat {{ redmine_home }}/config/locales/{{ redmine_lang }}.yml
  changed_when: false
  register: result
- name: set default lang data
  set_fact:
    default_lang_data: "{{ result.stdout | from_yaml }}"
- name: set customize lang data
  set_fact:
    redmine_custom_lang_data: "{{ default_lang_data | combine(redmine_customize_language, recursive=True) }}"
- name: output langage data file
  template:
    src: lang.yml.j2
    dest: "{{ redmine_home }}/config/locales/{{ redmine_lang }}.yml"
    mode: "0644"
  notify: restart redmine
- name: set git assume unchanged
  command: git update-index --assume-unchanged config/locales/{{ redmine_lang }}.yml
  args:
    chdir: "{{ redmine_home }}"
  tags:
    - skip_ansible_lint
