- name: set cron job param
  set_fact:
    redmine_reminder_param: "{{ redmine_send_reminders_cron_job.params | join(' ') if redmine_send_reminders_cron_job.params is defined else '' }}"
- name: set/unset send reminders job
  cron:
    name: Redmine send reminders job
    job: cd {{ redmine_home }} && bundle exec rake redmine:send_reminders {{ redmine_reminder_param }}
    hour: "{{ redmine_send_reminders_cron_job.hour | default('*') | string }}"
    minute: "{{ redmine_send_reminders_cron_job.minute | default('*') | string }}"
    user: "{{ redmine_user }}"
    state: "{{ 'present' if redmine_send_reminders_cron_job.enabled else 'absent' }}"
