---
- name: install ufw package
  apt:
    name: ufw
- name: install MariaDB packages
  apt:
    name: "{{ mariadb_packages }}"
- name: insrall python-pymysql package
  apt:
    name: python-pymysql
- name: create MariaDB Data directory
  file:
    path: "{{ mariadb_cfg.mysqld.innodb_data_home_dir }}"
    owner: mysql
    group: mysql
    mode: "0755"
    state: directory
  when: mariadb_cfg.mysqld.innodb_data_home_dir is defined
- name: create MariaDB custom setting file
  template:
    src: custom.cnf.j2
    dest: /etc/mysql/mariadb.conf.d/99-custom.cnf
    mode: "0644"
  notify: restart mariadb
- name: MariaDB is active and enable system on startup
  systemd:
    name: mariadb
    state: started
    enabled: true
- name: create / remove databases
  mysql_db:
    name: "{{ item.name }}"
    encoding: "{{ item.encoding | default(mariadb_default_charset) }}"
    collation: "{{ item.collation | default(mariadb_default_collation) }}"
    state: "{{ 'present' if item.state | default(true) else 'absent' }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  loop: "{{ mariadb_databases }}"
- name: create MariaDB users
  mysql_user:
    name: "{{ item.0.user | default(item.0.name) }}"
    password: "{{ item.0.password | default(omit) }}"
    host: "{{ item.1 }}"
    priv: "{{ item.0.name }}.*:ALL"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  loop: "{{ mariadb_databases | subelements('hosts', skip_missing=True) }}"
  no_log: true
- name: create / remove MariaDB users
  mysql_user:
    name: "{{ item.0.name }}"
    password: "{{ item.0.password }}"
    host: "{{ item.1 }}"
    priv: "{{ item.0.privs | join(',') }}"
    state: "{{ 'present' if item.0.state|default(true) else 'absent' }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  loop: "{{ mariadb_users | subelements('hosts') }}"
  no_log: true
- name: allow MySQL port
  ufw:
    rule: allow
    port: 3306
    proto: tcp
    from_ip: "{{ mariadb_allow_host }}"
  when: mariadb_allow_host is defined
