---
- name: install database adapter
  apt:
    name:
      - mariadb-client
      - python-pymysql
      - libmariadbclient-dev
- name: create database
  mysql_db:
    name: "{{ redmine_db_cfg.production.database }}"
    encoding: "{{ redmine_db_cfg.production.encoding }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
- name: create database user
  mysql_user:
    name: "{{ redmine_db_cfg.production.username }}"
    password: "{{ redmine_db_cfg.production.password }}"
    host: "{{ item }}"
    priv: "{{ redmine_db_cfg.production.database }}.*:ALL"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  loop:
    - localhost
    - 127.0.0.1
  no_log: true
