---
- name: install database adapter
  apt:
    name: "{{ item }}"
  with_items:
    - mariadb-client
    - python-mysqldb
    - libmariadbclient-dev
- name: create database
  mysql_db:
    name: "{{ redmine_db_cfg.production.database }}"
    encoding: "{{ redmine_db_cfg.production.encoding }}"
- name: create database user
  mysql_user:
    name: "{{ redmine_db_cfg.production.username }}"
    password: "{{ redmine_db_cfg.production.password }}"
    host: "{{ item }}"
    priv: "{{ redmine_db_cfg.production.database }}.*:ALL"
  with_items:
    - localhost
    - 127.0.0.1
